# Generated by Django 6.1 on 2026-09-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the user account is active. Defaults to False and user needs to verify email on signup before it can be set to True.",
            ),
        ),
    ]
